version: "3"

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: global_traefik
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" #traefik dashboard
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./certs:/etc/traefik/ssl:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

networks:
  default:
    external: 
      name: traefik_gateway